/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IZkWalletFactoryDiamond__factory } from "./IZkWalletFactoryDiamond__factory";
export { ZkWalletFactoryDiamond__factory } from "./ZkWalletFactoryDiamond__factory";
