/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IZkWalletFactoryDiamond,
  IZkWalletFactoryDiamondInterface,
} from "../../../../../contracts/diamond/zkWallet/factory/IZkWalletFactoryDiamond";

const _abi = [
  {
    inputs: [],
    name: "version",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IZkWalletFactoryDiamond__factory {
  static readonly abi = _abi;
  static createInterface(): IZkWalletFactoryDiamondInterface {
    return new utils.Interface(_abi) as IZkWalletFactoryDiamondInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IZkWalletFactoryDiamond {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IZkWalletFactoryDiamond;
  }
}
