/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IZkWalletDiamondBase } from "./IZkWalletDiamondBase";
export type { ZkWalletBaseMock } from "./ZkWalletBaseMock";
export type { ZkWalletDiamondBase } from "./ZkWalletDiamondBase";
