/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../common";

export declare namespace GuardianStorage {
  export type GuardianStruct = {
    hashId: BigNumberish;
    status: BigNumberish;
    timestamp: BigNumberish;
  };

  export type GuardianStructOutput = [BigNumber, number, BigNumber] & {
    hashId: BigNumber;
    status: number;
    timestamp: BigNumber;
  };
}

export declare namespace IGuardianInternal {
  export type GuardianDTOStruct = { hashId: BigNumberish };

  export type GuardianDTOStructOutput = [BigNumber] & { hashId: BigNumber };
}

export interface GuardianInterface extends utils.Interface {
  functions: {
    "addGuardian(uint256)": FunctionFragment;
    "cancelPendingGuardians()": FunctionFragment;
    "getGuardian(uint256)": FunctionFragment;
    "getGuardians(bool)": FunctionFragment;
    "numGuardians(bool)": FunctionFragment;
    "removeGuardian(uint256)": FunctionFragment;
    "removeGuardians((uint256)[])": FunctionFragment;
    "requireMajority((uint256)[])": FunctionFragment;
    "setInitialGuardians((uint256)[])": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "addGuardian"
      | "addGuardian(uint256)"
      | "cancelPendingGuardians"
      | "cancelPendingGuardians()"
      | "getGuardian"
      | "getGuardian(uint256)"
      | "getGuardians"
      | "getGuardians(bool)"
      | "numGuardians"
      | "numGuardians(bool)"
      | "removeGuardian"
      | "removeGuardian(uint256)"
      | "removeGuardians"
      | "removeGuardians((uint256)[])"
      | "requireMajority"
      | "requireMajority((uint256)[])"
      | "setInitialGuardians"
      | "setInitialGuardians((uint256)[])"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addGuardian",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "addGuardian(uint256)",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelPendingGuardians",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "cancelPendingGuardians()",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getGuardian",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getGuardian(uint256)",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getGuardians",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "getGuardians(bool)",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "numGuardians",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "numGuardians(bool)",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "removeGuardian",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "removeGuardian(uint256)",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "removeGuardians",
    values: [IGuardianInternal.GuardianDTOStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "removeGuardians((uint256)[])",
    values: [IGuardianInternal.GuardianDTOStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "requireMajority",
    values: [IGuardianInternal.GuardianDTOStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "requireMajority((uint256)[])",
    values: [IGuardianInternal.GuardianDTOStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "setInitialGuardians",
    values: [IGuardianInternal.GuardianDTOStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "setInitialGuardians((uint256)[])",
    values: [IGuardianInternal.GuardianDTOStruct[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "addGuardian",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addGuardian(uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelPendingGuardians",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelPendingGuardians()",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGuardian",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGuardian(uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGuardians",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGuardians(bool)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "numGuardians",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "numGuardians(bool)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeGuardian",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeGuardian(uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeGuardians",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeGuardians((uint256)[])",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requireMajority",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requireMajority((uint256)[])",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setInitialGuardians",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setInitialGuardians((uint256)[])",
    data: BytesLike
  ): Result;

  events: {
    "GuardianAdded(uint256,uint256)": EventFragment;
    "GuardianRemoved(uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "GuardianAdded"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "GuardianAdded(uint256,uint256)"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "GuardianRemoved"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "GuardianRemoved(uint256,uint256)"
  ): EventFragment;
}

export interface GuardianAddedEventObject {
  hashId: BigNumber;
  effectiveTime: BigNumber;
}
export type GuardianAddedEvent = TypedEvent<
  [BigNumber, BigNumber],
  GuardianAddedEventObject
>;

export type GuardianAddedEventFilter = TypedEventFilter<GuardianAddedEvent>;

export interface GuardianRemovedEventObject {
  hashId: BigNumber;
  effectiveTime: BigNumber;
}
export type GuardianRemovedEvent = TypedEvent<
  [BigNumber, BigNumber],
  GuardianRemovedEventObject
>;

export type GuardianRemovedEventFilter = TypedEventFilter<GuardianRemovedEvent>;

export interface Guardian extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: GuardianInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    addGuardian(
      hashId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "addGuardian(uint256)"(
      hashId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    cancelPendingGuardians(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "cancelPendingGuardians()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getGuardian(
      hashId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[GuardianStorage.GuardianStructOutput]>;

    "getGuardian(uint256)"(
      hashId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[GuardianStorage.GuardianStructOutput]>;

    getGuardians(
      includePendingAddition: boolean,
      overrides?: CallOverrides
    ): Promise<[GuardianStorage.GuardianStructOutput[]]>;

    "getGuardians(bool)"(
      includePendingAddition: boolean,
      overrides?: CallOverrides
    ): Promise<[GuardianStorage.GuardianStructOutput[]]>;

    numGuardians(
      includePendingAddition: boolean,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "numGuardians(bool)"(
      includePendingAddition: boolean,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    removeGuardian(
      hashId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "removeGuardian(uint256)"(
      hashId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    removeGuardians(
      guardians: IGuardianInternal.GuardianDTOStruct[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "removeGuardians((uint256)[])"(
      guardians: IGuardianInternal.GuardianDTOStruct[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    requireMajority(
      guardians: IGuardianInternal.GuardianDTOStruct[],
      overrides?: CallOverrides
    ): Promise<[void]>;

    "requireMajority((uint256)[])"(
      guardians: IGuardianInternal.GuardianDTOStruct[],
      overrides?: CallOverrides
    ): Promise<[void]>;

    setInitialGuardians(
      guardians: IGuardianInternal.GuardianDTOStruct[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "setInitialGuardians((uint256)[])"(
      guardians: IGuardianInternal.GuardianDTOStruct[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  addGuardian(
    hashId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "addGuardian(uint256)"(
    hashId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  cancelPendingGuardians(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "cancelPendingGuardians()"(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getGuardian(
    hashId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<GuardianStorage.GuardianStructOutput>;

  "getGuardian(uint256)"(
    hashId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<GuardianStorage.GuardianStructOutput>;

  getGuardians(
    includePendingAddition: boolean,
    overrides?: CallOverrides
  ): Promise<GuardianStorage.GuardianStructOutput[]>;

  "getGuardians(bool)"(
    includePendingAddition: boolean,
    overrides?: CallOverrides
  ): Promise<GuardianStorage.GuardianStructOutput[]>;

  numGuardians(
    includePendingAddition: boolean,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "numGuardians(bool)"(
    includePendingAddition: boolean,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  removeGuardian(
    hashId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "removeGuardian(uint256)"(
    hashId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  removeGuardians(
    guardians: IGuardianInternal.GuardianDTOStruct[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "removeGuardians((uint256)[])"(
    guardians: IGuardianInternal.GuardianDTOStruct[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  requireMajority(
    guardians: IGuardianInternal.GuardianDTOStruct[],
    overrides?: CallOverrides
  ): Promise<void>;

  "requireMajority((uint256)[])"(
    guardians: IGuardianInternal.GuardianDTOStruct[],
    overrides?: CallOverrides
  ): Promise<void>;

  setInitialGuardians(
    guardians: IGuardianInternal.GuardianDTOStruct[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "setInitialGuardians((uint256)[])"(
    guardians: IGuardianInternal.GuardianDTOStruct[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    addGuardian(
      hashId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "addGuardian(uint256)"(
      hashId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    cancelPendingGuardians(overrides?: CallOverrides): Promise<void>;

    "cancelPendingGuardians()"(overrides?: CallOverrides): Promise<void>;

    getGuardian(
      hashId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<GuardianStorage.GuardianStructOutput>;

    "getGuardian(uint256)"(
      hashId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<GuardianStorage.GuardianStructOutput>;

    getGuardians(
      includePendingAddition: boolean,
      overrides?: CallOverrides
    ): Promise<GuardianStorage.GuardianStructOutput[]>;

    "getGuardians(bool)"(
      includePendingAddition: boolean,
      overrides?: CallOverrides
    ): Promise<GuardianStorage.GuardianStructOutput[]>;

    numGuardians(
      includePendingAddition: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "numGuardians(bool)"(
      includePendingAddition: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    removeGuardian(
      hashId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "removeGuardian(uint256)"(
      hashId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    removeGuardians(
      guardians: IGuardianInternal.GuardianDTOStruct[],
      overrides?: CallOverrides
    ): Promise<void>;

    "removeGuardians((uint256)[])"(
      guardians: IGuardianInternal.GuardianDTOStruct[],
      overrides?: CallOverrides
    ): Promise<void>;

    requireMajority(
      guardians: IGuardianInternal.GuardianDTOStruct[],
      overrides?: CallOverrides
    ): Promise<void>;

    "requireMajority((uint256)[])"(
      guardians: IGuardianInternal.GuardianDTOStruct[],
      overrides?: CallOverrides
    ): Promise<void>;

    setInitialGuardians(
      guardians: IGuardianInternal.GuardianDTOStruct[],
      overrides?: CallOverrides
    ): Promise<void>;

    "setInitialGuardians((uint256)[])"(
      guardians: IGuardianInternal.GuardianDTOStruct[],
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "GuardianAdded(uint256,uint256)"(
      hashId?: BigNumberish | null,
      effectiveTime?: null
    ): GuardianAddedEventFilter;
    GuardianAdded(
      hashId?: BigNumberish | null,
      effectiveTime?: null
    ): GuardianAddedEventFilter;

    "GuardianRemoved(uint256,uint256)"(
      hashId?: BigNumberish | null,
      effectiveTime?: null
    ): GuardianRemovedEventFilter;
    GuardianRemoved(
      hashId?: BigNumberish | null,
      effectiveTime?: null
    ): GuardianRemovedEventFilter;
  };

  estimateGas: {
    addGuardian(
      hashId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "addGuardian(uint256)"(
      hashId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    cancelPendingGuardians(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "cancelPendingGuardians()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getGuardian(
      hashId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getGuardian(uint256)"(
      hashId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getGuardians(
      includePendingAddition: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getGuardians(bool)"(
      includePendingAddition: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    numGuardians(
      includePendingAddition: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "numGuardians(bool)"(
      includePendingAddition: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    removeGuardian(
      hashId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "removeGuardian(uint256)"(
      hashId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    removeGuardians(
      guardians: IGuardianInternal.GuardianDTOStruct[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "removeGuardians((uint256)[])"(
      guardians: IGuardianInternal.GuardianDTOStruct[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    requireMajority(
      guardians: IGuardianInternal.GuardianDTOStruct[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "requireMajority((uint256)[])"(
      guardians: IGuardianInternal.GuardianDTOStruct[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setInitialGuardians(
      guardians: IGuardianInternal.GuardianDTOStruct[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "setInitialGuardians((uint256)[])"(
      guardians: IGuardianInternal.GuardianDTOStruct[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addGuardian(
      hashId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "addGuardian(uint256)"(
      hashId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    cancelPendingGuardians(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "cancelPendingGuardians()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getGuardian(
      hashId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getGuardian(uint256)"(
      hashId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getGuardians(
      includePendingAddition: boolean,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getGuardians(bool)"(
      includePendingAddition: boolean,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    numGuardians(
      includePendingAddition: boolean,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "numGuardians(bool)"(
      includePendingAddition: boolean,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    removeGuardian(
      hashId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "removeGuardian(uint256)"(
      hashId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    removeGuardians(
      guardians: IGuardianInternal.GuardianDTOStruct[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "removeGuardians((uint256)[])"(
      guardians: IGuardianInternal.GuardianDTOStruct[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    requireMajority(
      guardians: IGuardianInternal.GuardianDTOStruct[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "requireMajority((uint256)[])"(
      guardians: IGuardianInternal.GuardianDTOStruct[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setInitialGuardians(
      guardians: IGuardianInternal.GuardianDTOStruct[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "setInitialGuardians((uint256)[])"(
      guardians: IGuardianInternal.GuardianDTOStruct[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
