/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as zkWallet from "./zkWallet";
export { ISimplicyDiamond__factory } from "./ISimplicyDiamond__factory";
export { ISimplicyWalletDiamond__factory } from "./ISimplicyWalletDiamond__factory";
export { SimplicyDiamond__factory } from "./SimplicyDiamond__factory";
export { SimplicyWalletDiamond__factory } from "./SimplicyWalletDiamond__factory";
