/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IZkWalletFactoryDiamond } from "./IZkWalletFactoryDiamond";
export type { ZkWalletFactoryDiamond } from "./ZkWalletFactoryDiamond";
