/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as base from "./base";
export type { base };
import type * as factory from "./factory";
export type { factory };
export type { ZkWalletDiamond } from "./ZkWalletDiamond";
