/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IEtherServiceFacet,
  IEtherServiceFacetInterface,
} from "../../../contracts/interfaces/IEtherServiceFacet";

const _abi = [
  {
    inputs: [],
    name: "etherServiceFacetVersion",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "getEtherBalance",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address payable",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "transferEther",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IEtherServiceFacet__factory {
  static readonly abi = _abi;
  static createInterface(): IEtherServiceFacetInterface {
    return new utils.Interface(_abi) as IEtherServiceFacetInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IEtherServiceFacet {
    return new Contract(address, _abi, signerOrProvider) as IEtherServiceFacet;
  }
}
