/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as zkWallet from "./zkWallet";
export type { zkWallet };
export type { ISimplicyDiamond } from "./ISimplicyDiamond";
export type { ISimplicyWalletDiamond } from "./ISimplicyWalletDiamond";
export type { SimplicyDiamond } from "./SimplicyDiamond";
export type { SimplicyWalletDiamond } from "./SimplicyWalletDiamond";
