/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as base from "./base";
export type { base };
import type * as extended from "./extended";
export type { extended };
import type * as metadata from "./metadata";
export type { metadata };
export type { IERC20 } from "./IERC20";
export type { IERC20Internal } from "./IERC20Internal";
export type { ISolidStateERC20 } from "./ISolidStateERC20";
